export enum MainActionTypes {
  SET_USER_PKEY = '@@MAIN/SET_USER_PKEY',
  SET_USER_DATA = '@@MAIN/SET_USER_DATA',
  SET_ALL_DOMAINS = '@@MAIN/SET_ALL_DOMAINS',
  SET_AVAILABLE = '@@MAIN/SET_AVAILABLE',
  SET_PARAMS = '@@MAIN/SET_PARAMS',
  SET_REGISTRATION_NAME = 'SET_REGISTRATION_NAME',

  LOAD_PARAMS = '@@MAIN/LOAD_PARAMS',
  LOAD_PARAMS_SUCCESS = '@@MAIN/LOAD_PARAMS_SUCCESS',
  LOAD_PARAMS_FAILURE = '@@MAIN/LOAD_PARAMS_FAILURE',

  GET_DOMAIN_NAME = '@@MAIN/GET_DOMAIN_NAME',
  GET_DOMAIN_NAME_SUCCESS = '@@MAIN/GET_DOMAIN_NAME_SUCCESS',
  GET_DOMAIN_NAME_FAILURE = '@@MAIN/GET_DOMAIN_NAME_FAILURE',

  GET_RATE = '@@MAIN/GET_RATE',
  GET_RATE_SUCCESS = '@@MAIN/GET_RATE_SUCCESS',
  GET_RATE_FAILURE = '@@MAIN/GET_RATE_FAILURE',
}
